### PR TITLE
Fix chromeLauncher import

### PR DESCRIPTION
**Pull request by Pluuk**

### CODE REVIEW

**Comment by freekmurze** [comment]
The current code seems to be working perfectly, why is this change needed?

**Comment by Pluuk** [comment]
Sorry, see #15. I got an error spatie/lighthouse-php 1.0.5, lighthouse@10.4.0, chromeLauncher@1.0.0. See https://github.com/GoogleChrome/chrome-launcher/releases/tag/v1.0.0, chromeLauncher is now published as an ESM.

**Comment by sweoggy** [comment]
Thanks, works great @Pluuk 

@freekmurze this fixes incompability with ChromeLauncher v1.0.0, which gives the following error message in main:

```sh
Could not run Lighthouse. Error : `/usr/src/app/vendor/spatie/lighthouse-php/bin/lighthouse.js:1
const chromeLauncher = require('chrome-launcher');
                       ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/src/app/node_modules/chrome-launcher/dist/index.js from /usr/src/app/vendor/spatie/lighthouse-php/bin/lighthouse.js not supported.
Instead change the require of index.js in /usr/src/app/vendor/spatie/lighthouse-php/bin/lighthouse.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/src/app/vendor/spatie/lighthouse-php/bin/lighthouse.js:1:24) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.5.0
`
```

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
